### ISSUE TITLE
Are FIDDLE features comparable across MIMIC and eICU? 

### ISSUE THREAD

**Issue by RudrakshTuwani** [MLD3/FIDDLE-experiments#3]
I want to run an experiment to assess whether a model trained on MIMIC is able to generalize on eICU. Are the FIDDLE features comparable as it is? If not, is it possible to carve out a subset that is comparable across the datasets?

**Comment by shengpu-tang** [comment]
Hello, for the feature sets used in the paper (and released [here](https://physionet.org/content/mimic-eicu-fiddle-feature/1.0.0/)), we did not attempt to map between MIMIC and eICU because we wanted to utilize everything available within each dataset that is potentially useful for the prediction tasks. Therefore, we created a separate feature set for each prediction task in each dataset. 

For your desired use case, I think this requires quite a bit of manual work. You could start with vital signs and lab values that are commonly used, but mapping flowsheet values in CHARTEVENTS/nurseCharting may take more time and clinical experience. You should also be careful about the bins generated from numeric variables; you can provide prespecified bins in the config file so that they're consistent across datasets (see Test 2.1 [here](https://github.com/MLD3/FIDDLE/blob/master/tests/small_test/Run.ipynb)). 

Other useful resources: 
- [MIMIC-Extract](https://arxiv.org/pdf/1907.08322.pdf) has 100+ clinical variables that should be available in both MIMIC and eICU
- [ICUnity](https://static1.squarespace.com/static/59d5ac1780bd5ef9c396eda6/t/5f2453ea2fd3481ead6d008f/1596216299715/69CameraReadySubmissionclinicalabstract.pdf) is a tool under development that helps match variables across EHR datasets

**Comment by RudrakshTuwani** [comment]
Thank you so much for the detailed response! Really appreciate it.
